### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by michae1a1ee** [dbrand666/docker-heyu-mqtt#3]
Hello.  Is there more detailed, step by step instructions available to get this installed and working on a HAOS virtual box?  My installation in not installed in Docker, and I don't have Docker added to my HAOS install as of yet.  Would really appreciate some direction as this is all completely new to me.

**Comment by hs6666** [comment]
mines virtualized on proxmox, you basically pass through the serial port using your virtualization platform to the HAOS VM, then specify the correct port in this addons settings page

ps you can see if your serial port is passed thorugh successfully by going to settings > system > all hardware, and the port is usually present there (normally: ttyUSB0)

i use this addon with about a dozen old x10 devices.... solid setup

**Comment by michae1a1ee** [comment]
Thank you very much.
I actually did figure this out in Oracle VirtualBox 7.0 just two days ago.
I finally figured out a COM Port combination that worked and didn't prevent
the Home Assistant session from failing to boot (enabling a few different
COM port options actually did!).  I'll try out your "PS" suggestion of how
to check the serial port from within Home Assistant soon, but it definitely
seems to be working now with the VirtualBox setting change.

One more note:  What I got working was the "X10 MQTT Gateway" Add-on.  I think that's different than this "docker-heyu-mqtt" product, correct?  This one allows for Dimming whereas the one I have implemented definitely does not.  Yes?

**Comment by hs6666** [comment]
haha, it was so long i set this up, just realised i'm using the mqtt gateway addon too :) yes, but i dont need dimming, plus i'm slowly moving over to esphome devices, cheap and cheerful and easy setup with the esphome addon

for me biggest pain is troubleshooting x10 when things dont work..... took me days to realise a dodgy power adaptor was making my x10 behave randomly, a real pain as my central heating was being controlled by an x10 device using the thermostat addin (house temp being monitored by a cheap esp8266 based thermostat device)

**Comment by michae1a1ee** [comment]
I don't have much in terms of x10 troubleshooting to do these days.  My x10 system is stable not being added to.  I am however considering getting a modern thermostat, once I take some time to figure out if the one I have now is connected to my existing automation panel through a proprietary wiring configuration or not.

**Comment by hs6666** [comment]
mine was stable for two years until it started playing up because of that dodgy power adaptor, pain as i rely on system and everything was showing as ok, very frustrating to troubleshoot, was just luck i discovered it, was about to rip out the system :)

what i do for my boiler thermostat was follow this guys video to get a working thermostat into HA.... (sensor.lounge_sensor_lounge_temperature)

then I add this code to my yaml file....

climate:
  - platform: generic_thermostat
    name: central heating
    unique_id: central heating thermostat
    heater: switch.central_heating_2
    target_sensor: sensor.lounge_sensor_lounge_temperature
    cold_tolerance: 0.0
    hot_tolerance: 0.3
    max_temp: 25
    min_temp: 15

then found the "switched live" terminal, which told my boiler to switch on/off, in my case it was 240v not 12v so I could just run an additional wire from that terminal to a power plug (live only connected inside the plug) with the plug then plugged into one of my x10 wall plugs, (called "switch.central_heating_2" as in above)

i know control my heating using a cheap tablet on the wall showing a dashboard with the thermostat entity as defined in the ymal file (its actually an old tablet that cant run ha app, but its running vnc viewer which then opens up firefox running inside a docker container on  my docker host with the dashboard set as the home page... but thats a whole different story!)

works flawlessly!

**Comment by dbrand666** [comment]
Hey. Sorry I missed this conversation. It sounds like you're both set though and not even using this version of the add-on. Should I close this issue then? 

I've been replacing the last of my x10 with esphone and Zigbee. X10 had a good run but I'm not gonna miss it.

**Comment by hs6666** [comment]
haha yes thats fine :)

(personally becasue my setup is rock solid..... I'm using an identical setup as yours homeassistant with x10/wifi with esphome/zigbee radios, but I'm only replacing my x10 units when/if a unit breaks down, or any x10 device were it would be nice to have state information)
